
package com.fenoreste_alestra.ws_client_tddImpl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://siscoop.endpoint.ws.syc.com/")
public class Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.fenoreste_alestra.ws_client_tdd.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception(String message,  com.fenoreste_alestra.ws_client_tdd.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception(String message,  com.fenoreste_alestra.ws_client_tdd.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.syc.ws.endpoint.siscoop.Exception
     */
    public com.fenoreste_alestra.ws_client_tdd.Exception getFaultInfo() {
        return faultInfo;
    }

}
