
package com.fenoreste_alestra.ws_client_tddImpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SiscoopAlternativeEndpointImplService", targetNamespace = "http://impl.siscoop.endpoint.ws.syc.com/", wsdlLocation = "http://192.168.110.85:6969/syc-siscoop/webservice/sagrada-familia/siscoopSecureService?wsdl")
public class SiscoopAlternativeEndpointImplService
    extends Service
{

    private final static URL SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_EXCEPTION;
    private final static QName SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_QNAME = new QName("http://impl.siscoop.endpoint.ws.syc.com/", "SiscoopAlternativeEndpointImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.110.85:6969/syc-siscoop/webservice/sagrada-familia/siscoopSecureService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_WSDL_LOCATION = url;
        SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_EXCEPTION = e;
    }

    public SiscoopAlternativeEndpointImplService() {
        super(__getWsdlLocation(), SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_QNAME);
    }

    public SiscoopAlternativeEndpointImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_QNAME, features);
    }

    public SiscoopAlternativeEndpointImplService(URL wsdlLocation) {
        super(wsdlLocation, SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_QNAME);
    }

    public SiscoopAlternativeEndpointImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_QNAME, features);
    }

    public SiscoopAlternativeEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiscoopAlternativeEndpointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SiscoopAlternativeEndpoint
     */
    @WebEndpoint(name = "SiscoopAlternativeEndpointImplPort")
    public SiscoopAlternativeEndpoint getSiscoopAlternativeEndpointImplPort() {
        return super.getPort(new QName("http://impl.siscoop.endpoint.ws.syc.com/", "SiscoopAlternativeEndpointImplPort"), SiscoopAlternativeEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiscoopAlternativeEndpoint
     */
    @WebEndpoint(name = "SiscoopAlternativeEndpointImplPort")
    public SiscoopAlternativeEndpoint getSiscoopAlternativeEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.siscoop.endpoint.ws.syc.com/", "SiscoopAlternativeEndpointImplPort"), SiscoopAlternativeEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_EXCEPTION!= null) {
            throw SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_EXCEPTION;
        }
        return SISCOOPALTERNATIVEENDPOINTIMPLSERVICE_WSDL_LOCATION;
    }

}
