
package com.fenoreste_alestra.ws_client_tddImpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.fenoreste_alestra.ws_client_tdd.*;
import com.fenoreste_alestra.ws_client_tdd.UpdateDemographicData.Cardinfo;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SiscoopAlternativeEndpoint", targetNamespace = "http://siscoop.endpoint.ws.syc.com/")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SiscoopAlternativeEndpoint {
	  @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public BalanceQueryResponseDto getBalanceQuery(
	        @WebParam(partName = "arg0", name = "arg0")
	        java.lang.String arg0
	    );

	   @WebMethod
	   @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public StockCardReplacementResponse stockCardReplacement(

	        @WebParam(partName = "arg0", name = "arg0")
	        java.lang.String arg0,
	        @WebParam(partName = "arg1", name = "arg1")
	        java.lang.String arg1
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public AsignaNIPResponse asignaNIP(
	        @WebParam(partName = "arg0", name = "arg0")
	        NipRequest request
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public UpdateDemographicDataResponse updateDemographicData(

	        @WebParam(partName = "pan", name = "pan")
	        java.lang.String pan,
	        @WebParam(partName = "cardinfo", name = "cardinfo")
	        com.fenoreste_alestra.ws_client_tdd.CardInfo cardinfo
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public DoWithdrawalAccountResponse doWithdrawalAccount(

	        @WebParam(partName = "pan", name = "pan")
	        java.lang.String pan,
	        @WebParam(partName = "amount", name = "amount")
	        java.lang.String amount
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public CardHolderInformationResponse getCardholderInformation(

	        @WebParam(partName = "pan", name = "pan")
	        java.lang.String pan
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public GetLastestTransactionsResponse getLastestTransactions(

	        @WebParam(partName = "pan", name = "pan")
	        java.lang.String pan,
	        @WebParam(partName = "numMaxOfRows", name = "numMaxOfRows")
	        int numMaxOfRows,
	        @WebParam(partName = "operationType", name = "operationType")
	        int operationType
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public CardLockResponse cardLock(

	        @WebParam(partName = "pan", name = "pan")
	        java.lang.String pan
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public DeleteIndividualLimitsResponse deleteIndividualLimits(

	        @WebParam(partName = "arg0", name = "arg0")
	        java.lang.String arg0
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public TemporaryLockResponse temporaryLock(

	        @WebParam(partName = "pan", name = "pan")
	        java.lang.String pan,
	        @WebParam(partName = "operationType", name = "operationType")
	        int operationType
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public ActivateCardResponse activateCard(

	        @WebParam(partName = "arg0", name = "arg0")
	        java.lang.String arg0
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public AssignmentAccountResponse assignmentAccount(
	        @WebParam(partName = "pan", name = "pan")
	        java.lang.String pan,
	        @WebParam(partName = "clientInfo", name = "clientInfo")
	        AssignamentAccountDto clientInfo
			//InfoClientRequest clientInfo
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public LoadBalanceResponse loadBalance(

	        @WebParam(partName = "pan", name = "pan")
	        java.lang.String pan,
	        @WebParam(partName = "amount", name = "amount")
	        java.lang.String amount
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public UpdateIndividualLimitsResponse updateIndividualLimits(

	        @WebParam(partName = "arg0", name = "arg0")
	        java.lang.String arg0,
	        @WebParam(partName = "arg1", name = "arg1")
	        IndividualLimitsDto arg1
	    );

	    @WebMethod
	    @WebResult(name = "return", targetNamespace = "http://ws.siscoop.creatoris.com/", partName = "return")
	    public SaveInformationClientBitMatchResponse saveInformationClientBitMatch(

	        @WebParam(partName = "arg0", name = "arg0")
	        InfoClientRequest arg0
	    );
}
